version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  service-a:
    build: ./service-a
    image: shabinaa/service-a:latest
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-b:
    build: ./service-b
    image: shabinaa/service-b:latest
    ports:
      - "9091:9091"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-c:
    build: ./service-c
    image: shabinaa/service-c:latest
    ports:
      - "9092:9092"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-d:
    build: ./service-d
    image: shabinaa/service-d:latest
    ports:
      - "9093:9093"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-e:
    build: ./service-e
    image: shabinaa/service-e:latest
    ports:
      - "9094:9094"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-f:
    build: ./service-f
    image: shabinaa/service-f:latest
    ports:
      - "9095:9095"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-g:
    build: ./service-g
    image: shabinaa/service-g:latest
    ports:
      - "9096:9096"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-h:
    build: ./service-h
    image: shabinaa/service-h:latest
    ports:
      - "9097:9097"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-i:
    build: ./service-i
    image: shabinaa/service-i:latest
    ports:
      - "9098:9098"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped

  service-j:
    build: ./service-j
    image: shabinaa/service-j:latest
    ports:
      - "9099:9099"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '384M'
    restart: unless-stopped