spring:
  application:
    name: service-c

server:
  port: 9092

management:
  endpoint:
    health:
      group:
        liveness:
          include: ping, diskSpace
  probes:
    enabled: true
  tracing:
    sampling:
      probability: 1.0


logging:
  level:
    org.springframework.web: INFO

tracing:
  url: http://localhost:4317
