spring:
  application:
    name: service-d

server:
  port: 9093

management:
  endpoint:
    health:
      group:
        liveness:
          include: ping, diskSpace
  probes:
    enabled: true
  tracing:
    sampling:
      probability: 1.0


logging:
  level:
    org.springframework.web: INFO

tracing:
  url: http://jaeger:4317
